set foreign_key_checks = 0;
truncate table AAR_USER;
truncate table SNS_ACCOUNT;
truncate table HOUSE;
truncate table ROOM;
truncate table HOME;
truncate table ITEM;
truncate table ITEM_SHAPE;
truncate table ITEM_SHAPE_CIRCLE;
truncate table ITEM_SHAPE_RECTANGLE;
truncate table ITEM_SHAPE_ELLIPSE;
truncate table SOUND_SOURCE;
truncate table FILE;
truncate table UNIVERSE;
truncate table UNIVERSE_HASHTAG;
truncate table UNIVERSE_LIKE;
truncate table HASHTAG;
truncate table SPACE;
truncate table CATEGORY;
truncate table PIECE;
truncate table SOUND;
truncate table BUSINESS_USER;
set foreign_key_checks = 1;
